name: hello-world
on: push
jobs:
  hello-world-job:
    run-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hallo_world.txt)"
